# Development/Testing Docker Compose Configuration
# Uses /tmp for ephemeral storage
# External port: 64181:80 (random unused port in 64xxx range)

services:
  weather:
    image: weather:dev
    container_name: weather-test
    restart: "no"

    environment:
      - CONFIG_DIR=/config
      - DATA_DIR=/data
      - LOG_DIR=/var/log/weather
      - PORT=80
      - ENV=development
      - DB_PATH=/data/db/weather.db
      - ADMIN_USER=administrator
      - ADMIN_PASSWORD=testpass123
      - DEV=true

    volumes:
      - /tmp/weather/rootfs/config/weather:/config
      - /tmp/weather/rootfs/data/weather:/data
      - /tmp/weather/rootfs/logs/weather:/var/log/weather

    ports:
      - "64181:80"

    networks:
      - weather

    healthcheck:
      test: ["CMD", "/usr/local/bin/weather", "--healthcheck"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

  # Optional: PostgreSQL for testing
  # postgres:
  #   image: postgres:16-alpine
  #   container_name: weather-postgres-test
  #   restart: "no"
  #
  #   environment:
  #     POSTGRES_DB: weather_test
  #     POSTGRES_USER: weather
  #     POSTGRES_PASSWORD: testpass
  #
  #   volumes:
  #     - /tmp/weather/rootfs/db/postgres:/var/lib/postgresql/data
  #
  #   networks:
  #     - weather

networks:
  weather:
    name: weather
    external: false
    driver: bridge
