package main

// AI.md PART 27: Swagger/OpenAPI Auto-Generation
// This file imports the auto-generated swagger docs
// Generated by: swag init -g src/main.go -o swaggerdocs
// TODO: Regenerate swagger docs after restructuring

// import (
// 	_ "github.com/apimgr/weather/swaggerdocs" // Import generated swagger docs
// )
