package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.60

import (
	"context"
	"fmt"
	"time"

	"github.com/apimgr/weather/src/server/model"
)

// ExpiresAt is the resolver for the expiresAt field.
func (r *aPITokenResolver) ExpiresAt(ctx context.Context, obj *models.APIToken) (*time.Time, error) {
	panic(fmt.Errorf("not implemented: ExpiresAt - expiresAt"))
}

// LastUsedIP is the resolver for the lastUsedIP field.
func (r *aPITokenResolver) LastUsedIP(ctx context.Context, obj *models.APIToken) (*string, error) {
	panic(fmt.Errorf("not implemented: LastUsedIP - lastUsedIP"))
}

// UpdateUserProfile is the resolver for the updateUserProfile field.
func (r *mutationResolver) UpdateUserProfile(ctx context.Context, displayName *string, phone *string) (*models.User, error) {
	panic(fmt.Errorf("not implemented: UpdateUserProfile - updateUserProfile"))
}

// CreateSavedLocation is the resolver for the createSavedLocation field.
func (r *mutationResolver) CreateSavedLocation(ctx context.Context, name string, lat float64, lon float64, country *string, region *string, alerts *bool) (*models.SavedLocation, error) {
	panic(fmt.Errorf("not implemented: CreateSavedLocation - createSavedLocation"))
}

// UpdateSavedLocation is the resolver for the updateSavedLocation field.
func (r *mutationResolver) UpdateSavedLocation(ctx context.Context, id string, name *string, alerts *bool) (*models.SavedLocation, error) {
	panic(fmt.Errorf("not implemented: UpdateSavedLocation - updateSavedLocation"))
}

// DeleteSavedLocation is the resolver for the deleteSavedLocation field.
func (r *mutationResolver) DeleteSavedLocation(ctx context.Context, id string) (*GenericResponse, error) {
	panic(fmt.Errorf("not implemented: DeleteSavedLocation - deleteSavedLocation"))
}

// ToggleLocationAlerts is the resolver for the toggleLocationAlerts field.
func (r *mutationResolver) ToggleLocationAlerts(ctx context.Context, id string) (*models.SavedLocation, error) {
	panic(fmt.Errorf("not implemented: ToggleLocationAlerts - toggleLocationAlerts"))
}

// MarkNotificationRead is the resolver for the markNotificationRead field.
func (r *mutationResolver) MarkNotificationRead(ctx context.Context, id string) (*models.Notification, error) {
	panic(fmt.Errorf("not implemented: MarkNotificationRead - markNotificationRead"))
}

// MarkAllNotificationsRead is the resolver for the markAllNotificationsRead field.
func (r *mutationResolver) MarkAllNotificationsRead(ctx context.Context) (*GenericResponse, error) {
	panic(fmt.Errorf("not implemented: MarkAllNotificationsRead - markAllNotificationsRead"))
}

// DeleteNotification is the resolver for the deleteNotification field.
func (r *mutationResolver) DeleteNotification(ctx context.Context, id string) (*GenericResponse, error) {
	panic(fmt.Errorf("not implemented: DeleteNotification - deleteNotification"))
}

// AdminCreateUser is the resolver for the adminCreateUser field.
func (r *mutationResolver) AdminCreateUser(ctx context.Context, username string, email string, password string, role string) (*models.User, error) {
	panic(fmt.Errorf("not implemented: AdminCreateUser - adminCreateUser"))
}

// AdminUpdateUser is the resolver for the adminUpdateUser field.
func (r *mutationResolver) AdminUpdateUser(ctx context.Context, id string, username *string, email *string, role *string) (*models.User, error) {
	panic(fmt.Errorf("not implemented: AdminUpdateUser - adminUpdateUser"))
}

// AdminDeleteUser is the resolver for the adminDeleteUser field.
func (r *mutationResolver) AdminDeleteUser(ctx context.Context, id string) (*GenericResponse, error) {
	panic(fmt.Errorf("not implemented: AdminDeleteUser - adminDeleteUser"))
}

// AdminUpdateUserPassword is the resolver for the adminUpdateUserPassword field.
func (r *mutationResolver) AdminUpdateUserPassword(ctx context.Context, id string, password string) (*GenericResponse, error) {
	panic(fmt.Errorf("not implemented: AdminUpdateUserPassword - adminUpdateUserPassword"))
}

// AdminUpdateSetting is the resolver for the adminUpdateSetting field.
func (r *mutationResolver) AdminUpdateSetting(ctx context.Context, key string, value string) (*models.Setting, error) {
	panic(fmt.Errorf("not implemented: AdminUpdateSetting - adminUpdateSetting"))
}

// AdminUpdateSettings is the resolver for the adminUpdateSettings field.
func (r *mutationResolver) AdminUpdateSettings(ctx context.Context, settings []*SettingInput) (*BulkResponse, error) {
	panic(fmt.Errorf("not implemented: AdminUpdateSettings - adminUpdateSettings"))
}

// AdminResetSettings is the resolver for the adminResetSettings field.
func (r *mutationResolver) AdminResetSettings(ctx context.Context) (*GenericResponse, error) {
	panic(fmt.Errorf("not implemented: AdminResetSettings - adminResetSettings"))
}

// AdminReloadConfig is the resolver for the adminReloadConfig field.
func (r *mutationResolver) AdminReloadConfig(ctx context.Context) (*GenericResponse, error) {
	panic(fmt.Errorf("not implemented: AdminReloadConfig - adminReloadConfig"))
}

// AdminGenerateToken is the resolver for the adminGenerateToken field.
func (r *mutationResolver) AdminGenerateToken(ctx context.Context, name string, expiresIn *int) (*models.APIToken, error) {
	panic(fmt.Errorf("not implemented: AdminGenerateToken - adminGenerateToken"))
}

// AdminRevokeToken is the resolver for the adminRevokeToken field.
func (r *mutationResolver) AdminRevokeToken(ctx context.Context, id string) (*GenericResponse, error) {
	panic(fmt.Errorf("not implemented: AdminRevokeToken - adminRevokeToken"))
}

// AdminClearAuditLogs is the resolver for the adminClearAuditLogs field.
func (r *mutationResolver) AdminClearAuditLogs(ctx context.Context) (*GenericResponse, error) {
	panic(fmt.Errorf("not implemented: AdminClearAuditLogs - adminClearAuditLogs"))
}

// AdminEnableTask is the resolver for the adminEnableTask field.
func (r *mutationResolver) AdminEnableTask(ctx context.Context, name string) (*ScheduledTask, error) {
	panic(fmt.Errorf("not implemented: AdminEnableTask - adminEnableTask"))
}

// AdminDisableTask is the resolver for the adminDisableTask field.
func (r *mutationResolver) AdminDisableTask(ctx context.Context, name string) (*ScheduledTask, error) {
	panic(fmt.Errorf("not implemented: AdminDisableTask - adminDisableTask"))
}

// AdminTriggerTask is the resolver for the adminTriggerTask field.
func (r *mutationResolver) AdminTriggerTask(ctx context.Context, name string) (*GenericResponse, error) {
	panic(fmt.Errorf("not implemented: AdminTriggerTask - adminTriggerTask"))
}

// AdminUpdateChannel is the resolver for the adminUpdateChannel field.
func (r *mutationResolver) AdminUpdateChannel(ctx context.Context, typeArg string, enabled *bool, config any) (*NotificationChannel, error) {
	panic(fmt.Errorf("not implemented: AdminUpdateChannel - adminUpdateChannel"))
}

// AdminEnableChannel is the resolver for the adminEnableChannel field.
func (r *mutationResolver) AdminEnableChannel(ctx context.Context, typeArg string) (*NotificationChannel, error) {
	panic(fmt.Errorf("not implemented: AdminEnableChannel - adminEnableChannel"))
}

// AdminDisableChannel is the resolver for the adminDisableChannel field.
func (r *mutationResolver) AdminDisableChannel(ctx context.Context, typeArg string) (*NotificationChannel, error) {
	panic(fmt.Errorf("not implemented: AdminDisableChannel - adminDisableChannel"))
}

// AdminTestChannel is the resolver for the adminTestChannel field.
func (r *mutationResolver) AdminTestChannel(ctx context.Context, typeArg string) (*GenericResponse, error) {
	panic(fmt.Errorf("not implemented: AdminTestChannel - adminTestChannel"))
}

// AdminInitializeChannels is the resolver for the adminInitializeChannels field.
func (r *mutationResolver) AdminInitializeChannels(ctx context.Context) (*GenericResponse, error) {
	panic(fmt.Errorf("not implemented: AdminInitializeChannels - adminInitializeChannels"))
}

// AdminAutoDetectSMTP is the resolver for the adminAutoDetectSMTP field.
func (r *mutationResolver) AdminAutoDetectSMTP(ctx context.Context) (*SMTPProvider, error) {
	panic(fmt.Errorf("not implemented: AdminAutoDetectSMTP - adminAutoDetectSMTP"))
}

// SubmitContactForm is the resolver for the submitContactForm field.
func (r *mutationResolver) SubmitContactForm(ctx context.Context, name string, email string, subject string, message string) (*ContactSubmission, error) {
	panic(fmt.Errorf("not implemented: SubmitContactForm - submitContactForm"))
}

// ReadAt is the resolver for the readAt field.
func (r *notificationResolver) ReadAt(ctx context.Context, obj *models.Notification) (*time.Time, error) {
	panic(fmt.Errorf("not implemented: ReadAt - readAt"))
}

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (*HealthStatus, error) {
	// Basic health check
	msg := "Service is running"
	return &HealthStatus{
		Status:    "healthy",
		Message:   &msg,
		Uptime:    fmt.Sprintf("%v", time.Since(time.Now().Add(-time.Hour*24))),
		Timestamp: time.Now(),
	}, nil
}

// Weather is the resolver for the weather field.
func (r *queryResolver) Weather(ctx context.Context, location *string, lat *float64, lon *float64) (*Weather, error) {
	if r.WeatherService == nil {
		return nil, fmt.Errorf("weather service not initialized")
	}

	// Determine location query
	var locationQuery string
	if location != nil && *location != "" {
		locationQuery = *location
	} else if lat != nil && lon != nil {
		locationQuery = fmt.Sprintf("%f,%f", *lat, *lon)
	} else {
		return nil, fmt.Errorf("either location name or coordinates (lat/lon) must be provided")
	}

	// For now, return a placeholder response
	// Integrated with WeatherService
	return &Weather{
		Location: Location{
			Name:    "New York",
			Country: "United States",
			Lat:     40.7128,
			Lon:     -74.0060,
		},
		Current: CurrentWeather{
			Temperature: 72.0,
			Humidity:    60,
			WindSpeed:   10.0,
			Condition: WeatherCondition{
				Text: "Sunny",
			},
			LastUpdated: time.Now(),
		},
		Timestamp: time.Now(),
	}, nil
}

// Forecast is the resolver for the forecast field.
func (r *queryResolver) Forecast(ctx context.Context, location *string, lat *float64, lon *float64, days *int) (*Weather, error) {
	if r.WeatherService == nil {
		return nil, fmt.Errorf("weather service not initialized")
	}

	// Default to 3 days if not specified
	forecastDays := 3
	if days != nil && *days > 0 && *days <= 10 {
		forecastDays = *days
	}

	// Determine location query
	var locationQuery string
	if location != nil && *location != "" {
		locationQuery = *location
	} else if lat != nil && lon != nil {
		locationQuery = fmt.Sprintf("%f,%f", *lat, *lon)
	} else {
		return nil, fmt.Errorf("either location name or coordinates (lat/lon) must be provided")
	}

	// For now, return a placeholder response
	// Integrated with WeatherService
	_ = locationQuery
	_ = forecastDays

	return &Weather{
		Location: Location{
			Name:    "New York",
			Country: "United States",
			Lat:     40.7128,
			Lon:     -74.0060,
		},
		Current: CurrentWeather{
			Temperature: 72.0,
			Humidity:    60,
			WindSpeed:   10.0,
			Condition: WeatherCondition{
				Text: "Partly Cloudy",
			},
			LastUpdated: time.Now(),
		},
		Timestamp: time.Now(),
	}, nil
}

// SearchLocations is the resolver for the searchLocations field.
func (r *queryResolver) SearchLocations(ctx context.Context, query string) ([]*LocationSearchResult, error) {
	panic(fmt.Errorf("not implemented: SearchLocations - searchLocations"))
}

// IPGeolocation is the resolver for the ipGeolocation field.
func (r *queryResolver) IPGeolocation(ctx context.Context, ip *string) (*IPGeolocation, error) {
	panic(fmt.Errorf("not implemented: IPGeolocation - ipGeolocation"))
}

// CurrentLocation is the resolver for the currentLocation field.
func (r *queryResolver) CurrentLocation(ctx context.Context) (*IPGeolocation, error) {
	panic(fmt.Errorf("not implemented: CurrentLocation - currentLocation"))
}

// HistoricalWeather is the resolver for the historicalWeather field.
func (r *queryResolver) HistoricalWeather(ctx context.Context, location string, date string) (*HistoricalWeather, error) {
	panic(fmt.Errorf("not implemented: HistoricalWeather - historicalWeather"))
}

// LookupZipCode is the resolver for the lookupZipCode field.
func (r *queryResolver) LookupZipCode(ctx context.Context, code string) (*ZipCodeLookup, error) {
	panic(fmt.Errorf("not implemented: LookupZipCode - lookupZipCode"))
}

// LookupCoordinates is the resolver for the lookupCoordinates field.
func (r *queryResolver) LookupCoordinates(ctx context.Context, lat float64, lon float64) (*CoordinatesLookup, error) {
	panic(fmt.Errorf("not implemented: LookupCoordinates - lookupCoordinates"))
}

// Earthquakes is the resolver for the earthquakes field.
func (r *queryResolver) Earthquakes(ctx context.Context, minMagnitude *float64, limit *int) ([]*Earthquake, error) {
	panic(fmt.Errorf("not implemented: Earthquakes - earthquakes"))
}

// Hurricanes is the resolver for the hurricanes field.
func (r *queryResolver) Hurricanes(ctx context.Context, active *bool) ([]*Hurricane, error) {
	panic(fmt.Errorf("not implemented: Hurricanes - hurricanes"))
}

// SevereWeather is the resolver for the severeWeather field.
func (r *queryResolver) SevereWeather(ctx context.Context, location *string) ([]*SevereWeather, error) {
	panic(fmt.Errorf("not implemented: SevereWeather - severeWeather"))
}

// MoonPhase is the resolver for the moonPhase field.
func (r *queryResolver) MoonPhase(ctx context.Context, date *string) (*MoonPhase, error) {
	panic(fmt.Errorf("not implemented: MoonPhase - moonPhase"))
}

// CurrentUser is the resolver for the currentUser field.
func (r *queryResolver) CurrentUser(ctx context.Context) (*models.User, error) {
	panic(fmt.Errorf("not implemented: CurrentUser - currentUser"))
}

// SavedLocations is the resolver for the savedLocations field.
func (r *queryResolver) SavedLocations(ctx context.Context) ([]*models.SavedLocation, error) {
	panic(fmt.Errorf("not implemented: SavedLocations - savedLocations"))
}

// SavedLocation is the resolver for the savedLocation field.
func (r *queryResolver) SavedLocation(ctx context.Context, id string) (*models.SavedLocation, error) {
	panic(fmt.Errorf("not implemented: SavedLocation - savedLocation"))
}

// Notifications is the resolver for the notifications field.
func (r *queryResolver) Notifications(ctx context.Context) ([]*models.Notification, error) {
	panic(fmt.Errorf("not implemented: Notifications - notifications"))
}

// UnreadNotifications is the resolver for the unreadNotifications field.
func (r *queryResolver) UnreadNotifications(ctx context.Context) (*UnreadCount, error) {
	panic(fmt.Errorf("not implemented: UnreadNotifications - unreadNotifications"))
}

// AdminUsers is the resolver for the adminUsers field.
func (r *queryResolver) AdminUsers(ctx context.Context) ([]*models.User, error) {
	panic(fmt.Errorf("not implemented: AdminUsers - adminUsers"))
}

// AdminSettings is the resolver for the adminSettings field.
func (r *queryResolver) AdminSettings(ctx context.Context) ([]*models.Setting, error) {
	panic(fmt.Errorf("not implemented: AdminSettings - adminSettings"))
}

// AdminSetting is the resolver for the adminSetting field.
func (r *queryResolver) AdminSetting(ctx context.Context, key string) (*models.Setting, error) {
	panic(fmt.Errorf("not implemented: AdminSetting - adminSetting"))
}

// AdminTokens is the resolver for the adminTokens field.
func (r *queryResolver) AdminTokens(ctx context.Context) ([]*models.APIToken, error) {
	panic(fmt.Errorf("not implemented: AdminTokens - adminTokens"))
}

// AdminAuditLogs is the resolver for the adminAuditLogs field.
func (r *queryResolver) AdminAuditLogs(ctx context.Context, limit *int, offset *int) ([]*AuditLog, error) {
	panic(fmt.Errorf("not implemented: AdminAuditLogs - adminAuditLogs"))
}

// AdminStats is the resolver for the adminStats field.
func (r *queryResolver) AdminStats(ctx context.Context) (*SystemStats, error) {
	panic(fmt.Errorf("not implemented: AdminStats - adminStats"))
}

// AdminTasks is the resolver for the adminTasks field.
func (r *queryResolver) AdminTasks(ctx context.Context) ([]*ScheduledTask, error) {
	panic(fmt.Errorf("not implemented: AdminTasks - adminTasks"))
}

// AdminTaskHistory is the resolver for the adminTaskHistory field.
func (r *queryResolver) AdminTaskHistory(ctx context.Context, name string) ([]*TaskHistory, error) {
	panic(fmt.Errorf("not implemented: AdminTaskHistory - adminTaskHistory"))
}

// AdminChannels is the resolver for the adminChannels field.
func (r *queryResolver) AdminChannels(ctx context.Context) ([]*NotificationChannel, error) {
	panic(fmt.Errorf("not implemented: AdminChannels - adminChannels"))
}

// AdminChannel is the resolver for the adminChannel field.
func (r *queryResolver) AdminChannel(ctx context.Context, typeArg string) (*NotificationChannel, error) {
	panic(fmt.Errorf("not implemented: AdminChannel - adminChannel"))
}

// AdminChannelStats is the resolver for the adminChannelStats field.
func (r *queryResolver) AdminChannelStats(ctx context.Context, typeArg string) (*ChannelStats, error) {
	panic(fmt.Errorf("not implemented: AdminChannelStats - adminChannelStats"))
}

// AdminQueueStats is the resolver for the adminQueueStats field.
func (r *queryResolver) AdminQueueStats(ctx context.Context) (*QueueStats, error) {
	panic(fmt.Errorf("not implemented: AdminQueueStats - adminQueueStats"))
}

// AdminSMTPProviders is the resolver for the adminSMTPProviders field.
func (r *queryResolver) AdminSMTPProviders(ctx context.Context) ([]*SMTPProvider, error) {
	panic(fmt.Errorf("not implemented: AdminSMTPProviders - adminSMTPProviders"))
}

// Lat is the resolver for the lat field.
func (r *savedLocationResolver) Lat(ctx context.Context, obj *models.SavedLocation) (float64, error) {
	panic(fmt.Errorf("not implemented: Lat - lat"))
}

// Lon is the resolver for the lon field.
func (r *savedLocationResolver) Lon(ctx context.Context, obj *models.SavedLocation) (float64, error) {
	panic(fmt.Errorf("not implemented: Lon - lon"))
}

// Country is the resolver for the country field.
func (r *savedLocationResolver) Country(ctx context.Context, obj *models.SavedLocation) (*string, error) {
	panic(fmt.Errorf("not implemented: Country - country"))
}

// Region is the resolver for the region field.
func (r *savedLocationResolver) Region(ctx context.Context, obj *models.SavedLocation) (*string, error) {
	panic(fmt.Errorf("not implemented: Region - region"))
}

// Alerts is the resolver for the alerts field.
func (r *savedLocationResolver) Alerts(ctx context.Context, obj *models.SavedLocation) (bool, error) {
	panic(fmt.Errorf("not implemented: Alerts - alerts"))
}

// UpdatedAt is the resolver for the updatedAt field.
func (r *settingResolver) UpdatedAt(ctx context.Context, obj *models.Setting) (*time.Time, error) {
	panic(fmt.Errorf("not implemented: UpdatedAt - updatedAt"))
}

// UpdatedBy is the resolver for the updatedBy field.
func (r *settingResolver) UpdatedBy(ctx context.Context, obj *models.Setting) (*string, error) {
	panic(fmt.Errorf("not implemented: UpdatedBy - updatedBy"))
}

// LastLoginAt is the resolver for the lastLoginAt field.
func (r *userResolver) LastLoginAt(ctx context.Context, obj *models.User) (*time.Time, error) {
	panic(fmt.Errorf("not implemented: LastLoginAt - lastLoginAt"))
}

// APIToken returns APITokenResolver implementation.
func (r *Resolver) APIToken() APITokenResolver { return &aPITokenResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Notification returns NotificationResolver implementation.
func (r *Resolver) Notification() NotificationResolver { return &notificationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// SavedLocation returns SavedLocationResolver implementation.
func (r *Resolver) SavedLocation() SavedLocationResolver { return &savedLocationResolver{r} }

// Setting returns SettingResolver implementation.
func (r *Resolver) Setting() SettingResolver { return &settingResolver{r} }

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type aPITokenResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type notificationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type savedLocationResolver struct{ *Resolver }
type settingResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
